### ISSUE TITLE
What about Hacker News comments?

### ISSUE THREAD

**Issue by xaprb** [ksimka/go-is-not-good#7]
Is it fair game to add summaries of comments on Hacker News?

Probably a bad idea. Idea that may be better: someone write some Big Data Machine Learning Cloud Based Neural Network parser that looks through HN comments and infers the gist of all the negative comments about Go, compiles and scores them, etc.

Write it in Go, of course.

**Comment by ksimka** [comment]
@xaprb I don't thinks it's a good idea, and that's why: it's **too easy** to throw your complaints as a comments to some conversation. Writing an article is hard. You must think twice before saying that X sucks because Y. Also an article is a responsibility: it's your blog, your personality, your reputation, you have contacts here (email, twitter, github), so you may get a feedback. So I personally think it's a good and simple filter for dont-think-too-long-write-some-shit comments. Have a really good comment? Make an article.

What about BDMLCBNN parser - I will immediately merge it when you make a PR with the code :)
